version: "3.8"

services:
  mysql-db:
    image: mysql
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_online_courses
    restart: always

  goc-api:
    depends_on:
      - mysql-db
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "2802:2802"
    image: goc-api:latest
    container_name: goc-api
    restart: always

  localtunnel:
    depends_on:
      - goc-api
    image: efrecon/localtunnel
    container_name: localtunnel
    restart: always
    links:
      - goc-api
    command:
      --local-host goc-api --port 2802 --subdomain mazzlookman

#  localtunnel:
#    depends_on:
#      - goc-api
#    image: node:20-alpine
#    command: >
#      sh -c "npm install -g localtunnel &&
#              lt --port 3000 --subdomain mazzlookman"
#    container_name: localtunnel
#    restart: always