version: "3.8"

services:
  mysql-db:
    image: mysql
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_pzn_restful_api
    restart: always

  pzn-api:
    depends_on:
      - mysql-db
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DB_DEV : docker
    ports:
      - "2802:2802"
    image: pzn-api:latest
    container_name: pzn-api
    restart: always

  localtunnel:
    depends_on:
      - pzn-api
    image: efrecon/localtunnel
    container_name: localtunnel
    restart: always
    links:
      - pzn-api
    command:
      --local-host pzn-api --port 2802 --subdomain mazzlookman

#  localtunnel:
#    depends_on:
#      - pzn-api
#    image: node:20-alpine
#    command: >
#      sh -c "npm install -g localtunnel &&
#              lt --port 3000 --subdomain mazzlookman"
#    container_name: localtunnel
#    restart: always